CREATE SCHEMA IF NOT EXISTS category_schema;
SET search_path TO category_schema;

CREATE TABLE IF NOT EXISTS categories (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
    );

CREATE INDEX IF NOT EXISTS idx_categories_name ON categories(name);