server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8032/main?currentSchema=compilation_schema
    username: main
    password: main
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: compilation_schema
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true

logging:
  level:
    ru.practicum: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full
      event-service:
        connect-timeout: 3000
        read-timeout: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always