server:
  port: 0

spring:
  application:
    name: compilation-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8032/main?currentSchema=compilation_schema
    username: main
    password: main
  jpa:
    hibernate:
      ddl-auto: none
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: compilation_schema
        format-sql: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full
      event-service:
        connect-timeout: 3000
        read-timeout: 3000

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.orm.jpa: WARN
    org.springframework.orm.jpa.JpaTransactionManager: WARN
    org.springframework.transaction: WARN
    org.springframework.transaction.interceptor: WARN

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always