<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.practicum</groupId>
        <artifactId>explore-with-me</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>stats</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>serialization</module>
        <module>collector</module>
        <module>aggregator</module>
        <module>analyzer</module>
        <module>stats-client</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <lombok.version>1.18.30</lombok.version>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <avro.version>1.11.3</avro.version>
        <protobuf.version>3.25.3</protobuf.version>
        <grpc.version>1.62.2</grpc.version>
        <kafka.version>3.6.0</kafka.version>
        <grpc-server.version>3.1.0.RELEASE</grpc-server.version>
        <grpc-client.version>3.1.0.RELEASE</grpc-client.version>
        <avro-schemas.version>0.0.1-SNAPSHOT</avro-schemas.version>
        <proto-schemas.version>0.0.1-SNAPSHOT</proto-schemas.version>
        <serializer.version>0.0.1-SNAPSHOT</serializer.version>
        <deserializer.version>0.0.1-SNAPSHOT</deserializer.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Apache dependencies -->
            <dependency>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro</artifactId>
                <version>${avro.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.kafka</groupId>
                <artifactId>kafka-clients</artifactId>
                <version>${kafka.version}</version>
            </dependency>

            <!-- Google dependencies -->
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf.version}</version>
            </dependency>

            <!-- gRPC dependencies -->
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-protobuf</artifactId>
                <version>${grpc.version}</version>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-stub</artifactId>
                <version>${grpc.version}</version>
            </dependency>

            <!-- Internal modules -->
            <dependency>
                <groupId>ru.practicum</groupId>
                <artifactId>avro-schemas</artifactId>
                <version>${avro-schemas.version}</version>
            </dependency>
            <dependency>
                <groupId>ru.practicum</groupId>
                <artifactId>proto-schemas</artifactId>
                <version>${proto-schemas.version}</version>
            </dependency>
            <dependency>
                <groupId>ru.practicum</groupId>
                <artifactId>serializer</artifactId>
                <version>${serializer.version}</version>
            </dependency>
            <dependency>
                <groupId>ru.practicum</groupId>
                <artifactId>deserializer</artifactId>
                <version>${deserializer.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                    <configuration>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>3.2.4</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>